//------------------------------------------------------------------------------
// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: enums.fbe
// FBE version: 1.14.5.0
//------------------------------------------------------------------------------

import ChronoxorFbe

// Fast Binary Encoding Enums receiver listener
public protocol ReceiverListener: ChronoxorFbe.ReceiveLogListener {
}

public extension ReceiverListener {
}
