// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding

@file:Suppress("UnusedImport", "unused")

package enums.fbe

import java.io.*
import java.lang.*
import java.lang.reflect.*
import java.math.*
import java.nio.charset.*
import java.time.*
import java.util.*

import fbe.*
import enums.*

import com.google.gson.*

class EnumUInt16Json : JsonSerializer<EnumUInt16>, JsonDeserializer<EnumUInt16>
{
    override fun serialize(src: EnumUInt16, typeOfSrc: Type, context: JsonSerializationContext): JsonElement
    {
        return JsonPrimitive(src.raw.toShort())
    }

    @Throws(JsonParseException::class)
    override fun deserialize(json: JsonElement, type: Type, context: JsonDeserializationContext): EnumUInt16
    {
        return EnumUInt16(json.asJsonPrimitive.asShort.toUShort())
    }
}
