// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: protoex.fbe
// Version: 1.2.0.0

@file:Suppress("UnusedImport", "unused")

package protoex.fbe

import java.io.*
import java.lang.*
import java.lang.reflect.*
import java.math.*
import java.nio.charset.*
import java.time.*
import java.util.*

import fbe.*
import protoex.*

// Fast Binary Encoding protoex final sender
@Suppress("MemberVisibilityCanBePrivate", "PropertyName")
open class FinalSender : fbe.Sender
{
    // Imported senders
    val protoSender: proto.fbe.FinalSender

    // Sender models accessors
    val OrderModel: OrderFinalModel
    val BalanceModel: BalanceFinalModel
    val AccountModel: AccountFinalModel

    constructor() : super(true)
    {
        protoSender = proto.fbe.FinalSender(buffer)
        OrderModel = OrderFinalModel(buffer)
        BalanceModel = BalanceFinalModel(buffer)
        AccountModel = AccountFinalModel(buffer)
    }

    constructor(buffer: Buffer) : super(buffer, true)
    {
        protoSender = proto.fbe.FinalSender(buffer)
        OrderModel = OrderFinalModel(buffer)
        BalanceModel = BalanceFinalModel(buffer)
        AccountModel = AccountFinalModel(buffer)
    }

    fun send(value: protoex.Order): Long
    {
        // Serialize the value into the FBE stream
        val serialized = OrderModel.serialize(value)
        assert(serialized > 0) { "protoex.Order serialization failed!" }
        assert(OrderModel.verify()) { "protoex.Order validation failed!" }

        // Log the value
        if (logging)
        {
            val message = value.toString()
            onSendLog(message)
        }

        // Send the serialized value
        return sendSerialized(serialized)
    }
    fun send(value: protoex.Balance): Long
    {
        // Serialize the value into the FBE stream
        val serialized = BalanceModel.serialize(value)
        assert(serialized > 0) { "protoex.Balance serialization failed!" }
        assert(BalanceModel.verify()) { "protoex.Balance validation failed!" }

        // Log the value
        if (logging)
        {
            val message = value.toString()
            onSendLog(message)
        }

        // Send the serialized value
        return sendSerialized(serialized)
    }
    fun send(value: protoex.Account): Long
    {
        // Serialize the value into the FBE stream
        val serialized = AccountModel.serialize(value)
        assert(serialized > 0) { "protoex.Account serialization failed!" }
        assert(AccountModel.verify()) { "protoex.Account validation failed!" }

        // Log the value
        if (logging)
        {
            val message = value.toString()
            onSendLog(message)
        }

        // Send the serialized value
        return sendSerialized(serialized)
    }

    // Send message handler
    override fun onSend(buffer: ByteArray, offset: Long, size: Long): Long { throw UnsupportedOperationException("protoex.fbe.Sender.onSend() not implemented!") }
}
