// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: fbe
// Version: 1.1.0.0

package fbe

// Fast Binary Encoding read buffer based on the constant byte buffer
type ReadBuffer struct {
    BaseBuffer
}

// Attach a given memory buffer
func (rb *ReadBuffer) AttachBuffer(buffer []byte, offset int, size int) {
    if buffer == nil {
        panic("Invalid buffer!")
    }
    if size <= 0 {
        panic("Invalid size!")
    }
    if offset > size {
        panic("Invalid offset!")
    }

    rb.buffer = buffer
    rb.size = size
    rb.offset = offset
}

// Reset the current read buffer and its offset
func (rb *ReadBuffer) Reset() {
    rb.size = 0
    rb.offset = 0
}
